config/routes.rb
Rails.application.routes.draw do
  get 'offres/offre'

  devise_for :utilisateurs
  get 'utilisateurs/home'
  get 'utilisateurs/myAccount'
  get 'utilisateurs/publicAccount'
  get 'offres/allOffres'
  get 'offres/singleOffre'
  get 'trajet/viewTrajet'
  get 'trajet/nouveauTrajet'
  get 'trajet/allTrajets'
  
  post 'trajet/nouveauTrajet' => 'trajet#create_trajet'

  get 'offres/creaOffres' => 'offres#creaOffres'
  post 'offres/creaOffres' => 'offres#crea_Offres'

  get 'offres/singleOffre/:id' => 'offres#singleOffre'

  root 'utilisateurs#home'

  devise_scope :utilisateur do
  get 'utilisateurs/sign_in', to: 'devise/sessions#new'
  post 'utilisateurs/sign_up', to: 'devise/session#create'

  get 'utilisateurs/inscription', to: 'devise/registrations#new'

  delete 'utilisateurs/profil', to: 'devise/registrations#destroy'

  get 'offres/recherche' => 'offres#recherche', as: 'recherche_offre'
  get 'utilisateurs/sign_out', to: 'devise/sessions#destroy'

  delete 'utilisateurs/sign_out', to: 'devise/sessions#destroy'
end

end

app/models/annonce.rb
class Annonce < ActiveRecord::Base

  belongs_to :utilisateur
  belongs_to :trajet
  belongs_to :categorie

  has_many :postules
  has_many :favories

end

app/models/categorie.rb
class Categorie < ActiveRecord::Base

  has_many :annonces

end

app/models/dateTrajet.rb
class DateTrajet < ActiveRecord::Base

  has_many :utilisateurs
  has_many :trajets

end

app/models/demande.rb
class Demande < ActiveRecord::Base

  has_many :utilisateurs
  has_many :trajets
  
end

app/models/favorie.rb
class Favorie < ActiveRecord::Base

  belongs_to :employe
  belongs_to :annonce
  
end

app/models/passage.rb
class Passage < ActiveRecord::Base

  has_many :utilisateurs
  has_many :trajets
  
end

app/models/postule.rb
class Postule < ActiveRecord::Base

  belongs_to :employe
  belongs_to :annonce
  
end

app/models/trajet.rb
class Trajet < ActiveRecord::Base

  has_many :dates
  has_many :demandes
  has_many :passages

  belongs_to :annonce
  
end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base

  has_many :annonces
  has_many :dates
  has_many :demandes
  has_many :passages

  belongs_to :annonce
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:nom, :prenom, :email, :sexe, :tel, :adresse, :dateNaiss, :codePostal, :ville, :description, :password, :password_confirmation)}
  end


end

app/controllers/offres_controller.rb
class OffresController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def offre

  end

  def crea_Offres
    if current_utilisateur
      annonce = Annonce.new
      annonce.utilisateur_id = current_utilisateur.id
      annonce.nom = params[:nomOffre]
      annonce.nomOrganisme = params[:nomOrganisme]
      annonce.categorie_id = params[:categorie_id]

      annonce.adresse = params[:adresse]
      annonce.courteDescr = params[:courteDescr]
      annonce.descritif = params[:descritif]
      annonce.dateExpiration = params[:dateExpiration]
      annonce.dateDebut = params[:dateDebut]

      annonce.typeContrat = params[:typeContrat]
      annonce.codePostal = params[:codePostal]
      annonce.ville = params[:ville]



      if annonce.valid?
        annonce.save
        flash[:info] = "L'annonce a été créée"

        redirect_to "/utilisateurs/home"
      else
        flash[:info] = "Il manque des informations"
        redirect_to "/offre/creaOffres"
      end
    end
  end

  def allOffres
    @annonces = Annonce.all
  end

  def recherche
    @annonce = Annonce.where(["nom LIKE ?", "%#{params[:search]}%"])
  end


  def  updateOffre
    Annonce.find(params[]).update categorie_id = params[:categorie_id],
                                  dateExpiration = params[:dateExpiration],
                                  descritif = params[:descritif],
                                  dateDebut = params[:dateDebut],
                                  typeContrat = params[:typeContrat]
    redirect_to(:back)

  end

  def destroyOffre
    Annonce.find(params[:id]).destroy
    flash[:info] = "L'annonce est supprimée"
    redirect_to root_path
  end

  def creaOffres
    @liste = Categorie.all
  end

  def singleOffre
    @annonceSolo = Annonce.find(params[:id])
  end
end

app/controllers/trajet_controller.rb
class TrajetController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def create_trajet
    if current_utilisateur
      trajet = Trajet.new
      trajet.annonce_id = params[:annonce_id]
      trajet.dateDebut = params[:dateDebut]
      trajet.dateFin = params[:dateFin]
      trajet.destination = params[:destination]
      trajet.typeVehicule = params[:typeVehicule]

      if trajet.valid?
        trajet.save
        flash[:info] = "Le trajet a été créé"

      end

      redirect_to "/utilisateurs/home"
    else
      flash[:info] = "Il manque des informations"
      redirect_to "/trajet/nouveauTrajet"
    end
  end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/trajet_helper.rb
module TrajetHelper
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="uza - Model Agency HTML5 Template">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>JustJob - Handi Intérim</title>

    <!-- Favicon -->
    <link rel="icon" href="/style/img/core-img/favicon.ico">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="/style/style.css">

</head>

<body>

    <!-- Preloader -->
    <div id="preloader">
        <div class="wrapper">
            <div class="cssload-loader"></div>
        </div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header-area">
    <!-- Main Header Start -->
    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <!-- Classy Menu -->
            <nav class="classy-navbar justify-content-between" id="uzaNav">

                <!-- Logo -->
                <!--
                <a class="nav-brand" href="index.html"><img src="./img/core-img/logo.png" alt=""></a>
                -->
                <a class="nav-brand" href="/utilisateurs/home"><h3>JustJob</h3></a>

                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>

                <!-- Menu -->
                <div class="classy-menu">
                    <!-- Menu Close Button -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>

                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul id="nav">
                            <li><a href="/utilisateurs/home">Accueil</a></li>
                            <li><a href="/trajet/allTrajets">Trajets</a></li>
                            <% if utilisateur_signed_in? %>
                                <li><a href="/offres/creaOffres">Nouvelle offre</a></li>
                            <% end %>
                        </ul>

                        <!-- Get A Quote -->
                        <div class="get-a-quote ml-4 mr-3">
                            <a href="/offres/allOffres" class="btn uza-btn btn-2">Offres d'emploi</a>
                        </div>

                        <!-- Login / Register -->
                        <% if utilisateur_signed_in? %>
                            <div class="login-register-btn mx-3">
                                <a href="/utilisateurs/myAccount"><%=current_utilisateur.prenom%> <%=current_utilisateur.nom%></a>
                            </div>
                        <% else %>
                            <div class="login-register-btn mx-3">
                                <a href="/utilisateurs/sign_in">Se connecter</a> / <a href="/utilisateurs/sign_up">S'inscrire</a>
                            </div>
                        <% end %>
                    </div>
                    <!-- Nav End -->

                </div>
            </nav>
        </div>
    </div>
</header>
    <!-- ***** Header Area End ***** -->
    <%= notice %>
    <%= alert %>
    <%= yield %>



    <!-- ***** Footer Area Start ***** -->
    <footer class="footer-area section-padding-80-0">
        <div class="container">
            <div class="row justify-content-between">

                <!-- Single Footer Widget -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">
                        <!-- Widget Title -->
                        <h4 class="widget-title">Handi Intérim</h4>

                        <!-- Footer Content -->
                        <div class="footer-content mb-15">
                            <h3>06 63 78 65 81</h3>
                            <p>julien.falentin@gmail.com</p>
                        </div>
                    </div>
                </div>

                <!-- Single Footer Widget -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">
                        <!-- Widget Title -->
                        <h4 class="widget-title">Accès rapides</h4>

                        <!-- Nav -->
                        <nav>
                            <ul class="our-link">
                                <li><a href="/utilisateurs/home">Présentation</a></li>
                                <li><a href="/offres/allOffres">Offres d'emploi</a></li>
                                <li><a href="/offres/creaOffres">Nouvelle offre</a></li>
                                <li><a href="/utilisateurs/myAccount">Mon compte</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <!-- Single Footer Widget -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">
                        <!-- Widget Title -->
                        <h4 class="widget-title">Resources</h4>

                        <!-- Nav -->
                        <nav>
                            <ul class="our-link">
                                <li><a href="#">Mentions légales</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <!-- Single Footer Widget -->
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="single-footer-widget mb-80">
                        <!-- Widget Title -->
                        <h4 class="widget-title">À propos du site</h4>
                        <p>Site réalisé par le département informatique de l'IUT Nancy-Charlemagne pour l'association Handi Intérim.</p>

                        <!-- Copywrite Text -->
                        <div class="copywrite-text mb-30">
                            <p>&copy; Copyright 2019 <a href="#">Colorlib</a>.</p>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </footer>
    <!-- ***** Footer Area End ***** -->

    <!-- ******* All JS Files ******* -->
    <!-- jQuery js -->
    <script src="/style/js/jquery.min.js"></script>
    <!-- Popper js -->
    <script src="/style/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/style/js/bootstrap.min.js"></script>
    <!-- All js -->
    <script src="/style/js/uza.bundle.js"></script>
    <!-- Active js -->
    <script src="/style/js/default-assets/active.js"></script>

</body>

</html>

app/views/offres/allOffres.html.erb
<!-- ***** Breadcrumb Area Start  ***** -->
<div class="breadcrumb-area">
  <div class="container h-100">
    <div class="row h-100 align-items-end">
      <div class="col-12">
        <div class="breadcumb--con">
          <h2 class="title">Offres d'emploi</h2>
        </div>
      </div>
    </div>
  </div>

  <section class="uza-newsletter-area" style="margin-top: 30px;">
    <div class="container nl-form mb-80">
      <%= form_tag recherche_offre_path, :method => 'get' do %>
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <%= text_field_tag :search, params[:search], autofocus: true%>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="form-group">
              <%= submit_tag "Rechercher" %>
            </div>
          </div>
        </div>
      <% end  %>
    </div>
  </section>

  <!-- Background Curve -->
  <div class="breadcrumb-bg-curve">
    <img src="/style/img/core-img/curve-5.png" alt="">
  </div>
</div>
<!-- ***** Breadcrumb Area End ***** -->

<!-- ***** Blog Area Start ***** -->
<div class="uza-blog-area section-padding-80">
  <div class="container">
    <div class="row">

      <% @annonces.each do |a| %>
        <div class="col-12 col-lg-4">
          <div class="single-blog-post bg-img mb-80">
            <!-- Post Content -->
            <div class="post-content">
              <span class="post-date">Expire le <%= a.dateExpiration %></span>
              <a href="#" class="post-title"><%= a.nom %></a>
              <p> Organisme : <%= a.nomOrganisme %></p>
              <p><%= a.courteDescr %>></p>
              <a href="/offres/singleOffre/<%= a.id %>" class="read-more-btn">Voir l'offre <i class="arrow_carrot-2right"></i></a>
            </div>
          </div>
        </div>
      <% end %>



    </div>
  </div>
</div>
<!-- ***** Blog Area End ***** -->

app/views/offres/creaOffres.html.erb
<!-- ***** Breadcrumb Area Start ***** -->
    <div class="breadcrumb-area">
        <div class="container h-100">
            <div class="row h-100 align-items-end">
                <div class="col-12">
                    <div class="breadcumb--con">
                        <h2 class="title">Nouvelle offre</h2>
                    </div>
                </div>
            </div>
        </div>

        <!-- Background Curve -->
        <div class="breadcrumb-bg-curve">
            <img src="/style/img/core-img/curve-5.png" alt="">
        </div>
    </div>
    <!-- ***** Breadcrumb Area End ***** -->

    <!-- ***** Blog Area Start ***** -->
    <section class="uza-newsletter-area">
        <div class="container">
            <form action="creaOffres" method="post">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <input type="text" class="form-control mb-30" name="nomOffre" placeholder="Nom de l'offre">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <input type="text" class="form-control mb-30" name="nomOrganisme" placeholder="Nom de l'organisme">
                        </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <select name="categorie" id="categorie">
                          <option> Choisir une catégorie</option>
                          <% @liste.each do |cate| %>
                            <option value=<%= cate.id %>><%= cate.titre %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <input type="text" class="form-control mb-30" name="adresse" placeholder="Adresse du lieu de travail">
                        </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <input type="text" class="form-control mb-30" name="ville" placeholder="Ville">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <input type="number" class="form-control mb-30" name="codePostal" placeholder="Exemple : 54000">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <select name="categorie" id="categorie">
                          <option value="CDI" selected>CDI</option>
                          <option value="CDD">CDD</option>
                          <option value="Interimaire">Intérimaire</option>
                        </select>
                      </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <textarea class="form-control mb-30" name="courteDescr" rows="2" cols="80" placeholder="Courte description"></textarea>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <textarea class="form-control mb-30" name="descritif" rows="14" cols="80" placeholder="Contenu de l'offre"></textarea>
                        </div>
                    </div>
                    <div class="col-12">
                      <div class="form-group">
                        <label> Date d'expiration de l'offre </label>
                        <input type="date" class="form-control mb-30" name="dateExpiration"/>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="form-group">
                        <label> Date de début de l'emploi </label>
                        <input type="date" class="form-control mb-30" name="dateDebut"/>
                      </div>
                    </div>

                    <div class="col-12">
                        <button class="btn uza-btn btn-2" data-animation="fadeInUp" data-delay="700ms">Ajouter l'offre</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <!-- ***** Blog Area End ***** -->

app/views/utilisateurs/home.html.erb
<!-- ***** Welcome Area Start ***** -->
<section class="welcome-area">
        <div class="welcome-slides owl-carousel">

            <!-- Single Welcome Slide -->
            <div class="single-welcome-slide">
                <!-- Background Curve -->
                <div class="background-curve">
                    <img src="/style/img/core-img/curve-1.png" alt="">
                </div>

                <!-- Welcome Content -->
                <div class="welcome-content h-100">
                    <div class="container h-100">
                        <div class="row h-100 align-items-center">
                            <!-- Welcome Text -->
                            <div class="col-12 col-md-6">
                                <div class="welcome-text">
                                    <h2 data-animation="fadeInUp" data-delay="100ms">Recherches des <br> offres d'<span>emploi</span></h2>
                                    <a href="/offres/allOffres" class="btn uza-btn btn-2" data-animation="fadeInUp" data-delay="700ms">Offres d'emploi</a>
                                </div>
                            </div>
                            <!-- Welcome Thumbnail -->
                            <div class="col-12 col-md-6">
                                <div class="welcome-thumbnail">
                                    <img src="/style/img/bg-img/ordinateur-job.png" alt="" data-animation="slideInRight" data-delay="400ms">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Single Welcome Slide -->
            <div class="single-welcome-slide">
                <!-- Background Curve -->
                <div class="background-curve">
                    <img src="/style/img/core-img/curve-1.png" alt="">
                </div>

                <!-- Welcome Content -->
                <div class="welcome-content h-100">
                    <div class="container h-100">
                        <div class="row h-100 align-items-center">
                            <!-- Welcome Text -->
                            <div class="col-12 col-md-6">
                                <div class="welcome-text">
                                    <h2 data-animation="fadeInUp" data-delay="100ms">Recherches des<br> propositions de<span> transport</span></h2>
                                    <a href="/trajet/viewTrajet" class="btn uza-btn btn-2" data-animation="fadeInUp" data-delay="700ms">Voir les propositions</a>
                                    <a href="/trajet/nouveauTrajet" class="btn uza-btn btn-2" data-animation="fadeInUp" data-delay="700ms">Proposer un nouveau trajet</a>
                                </div>
                            </div>
                            <!-- Welcome Thumbnail -->
                            <div class="col-12 col-md-6">
                                <div class="welcome-thumbnail">
                                    <img src="/style/img/bg-img/ordinateur-job.png" alt="" data-animation="slideInRight" data-delay="400ms">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Single Welcome Slide -->
            <div class="single-welcome-slide">
                <!-- Background Curve -->
                <div class="background-curve">
                    <img src="/style/img/core-img/curve-1.png" alt="">
                </div>

                <!-- Welcome Content -->
                <div class="welcome-content h-100">
                    <div class="container h-100">
                        <div class="row h-100 align-items-center">
                            <!-- Welcome Text -->
                            <div class="col-12 col-md-6">
                                <div class="welcome-text">
                                    <h2 data-animation="fadeInUp" data-delay="100ms">Envoyez des <br> offres d'<span>emploi</span></h2>
                                    <% if utilisateur_signed_in? %>
                                        <a href="/offres/creaOffres" class="btn uza-btn btn-2" data-animation="fadeInUp" data-delay="700ms">Nouvelle offre</a>
                                    <% else %>
                                        <a href="/utilisateurs/sign_in" class="btn uza-btn btn-2" data-animation="fadeInUp" data-delay="700ms">Me connecter</a>
                                    <% end %>
                                </div>
                            </div>
                            <!-- Welcome Thumbnail -->
                            <div class="col-12 col-md-6">
                                <div class="welcome-thumbnail">
                                    <img src="/style/img/bg-img/ordinateur-job.png" alt="" data-animation="slideInRight" data-delay="400ms">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!-- ***** Welcome Area End ***** -->
    <!-- ***** About Us Area Start ***** -->
    <section class="uza-about-us-area section-padding-80">
        <div class="container">
            <div class="row align-items-center">
                <!-- About Thumbnail -->
                <div class="col-12 col-lg-6">
                    <div class="about-us-thumbnail mb-80">
                        <img src="/style/img/bg-img/2.jpg" alt="">
                        <!-- Video Area -->
                        <!--
                        <div class="uza-video-area hi-icon-effect-8">
                            <a href="https://www.youtube.com/watch?v=sSakBz_eYzQ" class="hi-icon video-play-btn"><i class="fa fa-play" aria-hidden="true"></i></a>
                        </div>
                        -->
                    </div>
                </div>

                <!-- About Us Content -->
                <div class="col-12 col-lg-6">
                    <div class="section-heading mb-5">
                        <h2>Comment ça marche ?</h2>
                    </div>

                    <div class="about-us-content mb-80">
                        <div class="about-tab-area">
                            <ul class="nav nav-tabs mb-50" id="mona_modelTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="tab1" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">CRÉER UN COMPTE</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="tab2" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">CANDIDATER</a>
                                </li>
                            </ul>
                        </div>

                        <!-- Mona Tab Content -->
                        <div class="about-tab-content">
                            <div class="tab-content" id="mona_modelTabContent">
                                <div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="tab1">
                                    <!-- Tab Content Text -->
                                    <div class="tab-content-text">
                                        <p>La première étape est de créer votre compte afin de pouvoir vous connecter et consulter ou créer des annonces. Vous pouvvez ainsi sauvegarder les annonces que vous souhaitez garder de côté.</p>
                                        <a href="/utilisateurs/sign_up" style="" class="btn uza-btn mt-30">Créer un compte</a>
                                    </div>
                                </div>

                                <div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="tab2">
                                    <!-- Tab Content Text -->
                                    <div class="tab-content-text">
                                        <p>Une fois votre compte créé vous pourrez consulter les annonces disponibles et candidater pour certaines d'entre elles en envoyer votre CV.</p>
                                        <a href="/offres/allOffres" class="btn uza-btn mt-30">Voir les offres</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About Background Pattern -->
        <div class="about-bg-pattern">
            <img src="/style/img/core-img/curve-2.png" alt="">
        </div>
    </section>
    <!-- ***** About Us Area End ***** -->

    <!-- ***** Blog Area Start ***** -->
    <section class="uza-blog-area">
            <!-- Background Curve -->
            <div class="blog-bg-curve">
                <img src="/style/img/core-img/curve-4.png" alt="">
            </div>

            <div class="container">
                <div class="row">
                    <!-- Section Heading -->
                    <div class="col-12">
                        <div class="section-heading text-center">
                            <h2>Dernières offres</h2>
                            <p>Voici les dernières offres postées sur JustJob</p>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <!-- Single Blog Post -->
                    <div class="col-12 col-lg-4">
                        <div class="single-blog-post bg-img mb-80">
                            <!-- Post Content -->
                            <div class="post-content">
                                <span class="post-date"><span>07</span> février 2019 à 10h27</span>
                                <a href="#" class="post-title">Nom de l'offre</a>
                                <p>Description de l'offre avec détails et tout ce qui va bien.</p>
                                <a href="#" class="read-more-btn">Voir l'offre <i class="arrow_carrot-2right"></i></a>
                            </div>
                        </div>
                    </div>

                    <!-- Single Blog Post -->
                    <div class="col-12 col-lg-4">
                        <div class="single-blog-post bg-img mb-80">
                            <!-- Post Content -->
                            <div class="post-content">
                                <span class="post-date"><span>29</span> janvier 2019 à 11h03</span>
                                <a href="#" class="post-title">Nom de l'offre</a>
                                <p>Description de l'offre avec détails et tout ce qui va bien.</p>
                                <a href="#" class="read-more-btn">Voir l'offre <i class="arrow_carrot-2right"></i></a>
                            </div>
                        </div>
                    </div>

                    <!-- Single Blog Post -->
                    <div class="col-12 col-lg-4">
                        <div class="single-blog-post bg-img mb-80">
                            <!-- Post Content -->
                            <div class="post-content">
                                <span class="post-date"><span>14</span> janvier 2019 à 17h34</span>
                                <a href="#" class="post-title">Nom de l'offre</a>
                                <p>Description de l'offre avec détails et tout ce qui va bien.</p>
                                <a href="#" class="read-more-btn">Voir l'offre <i class="arrow_carrot-2right"></i></a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!-- ***** Blog Area End ***** -->